name: Build Unity Dedicated Server
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Unity
        run: |
          curl -sL https://beta.unity3d.com/download/71ddac4d5d8e/UnitySetup-2021.3.11f1 | bash -s -- --install-location /opt/unity --components "Unity.Linux"
          sudo ln -s /opt/unity/Editor/Unity /usr/local/bin/unity

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Build Unity Dedicated Server
        run: |
          unity -quit -batchmode -buildTarget Linux64 -customBuildTarget ServerLinux64 -customBuildName "MyServer" -customBuildPath ./build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: UnityDedicatedServerBuild
          path: build
