name: AvarikCI Build 🎮

on:
  workflow_dispatch:

env:
  PROJECT_ID: agones-test-385708
  IMAGE_NAME: server_test_rifai
  OUTPUT_PATH: Builds/Server

jobs:
  buildLinuxGameServer:
    name: Build for Linux Server
    runs-on: ubuntu-latest
    container:
      image: unityci/editor:ubuntu-2021.3.7f1-linux-il2cpp-1.1.2
      options: --user 0
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Git
        run: |
          apt-get update
          apt-get install -y git

      - name: Build Unity Dedicated Server
        run: |
          mkdir -p ${{ env.OUTPUT_PATH }}
          /opt/unity/Editor/Unity \
            -quit \
            -batchmode \
            -nographics \
            -buildTarget Linux64 \
            -executeMethod BuildScript.BuildServer \
            -serial "${{ secrets.UNITY_SERIAL }}" \
            -username "${{ secrets.UNITY_EMAIL }}" \
            -password "${{ secrets.UNITY_PASSWORD }}" \
            -outputPath "${{ env.OUTPUT_PATH }}/UnityServer.x86_64" \
            -silent-crashes

      - name: Get Commit ID
        id: commit_id
        run: echo "::set-output name=commit_id::${GITHUB_SHA}"
      
      - name: Get Branch Name
        id: branch_name
        run: echo "::set-output name=branch_name::${GITHUB_REF#refs/heads/}"

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M:%S')"

      - name: 'Authenticate to Google Cloud'
        id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          
      
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Encode GCP_SA_KEY
        id: encode_key
        run: echo -n "${{ secrets.GCP_SA_KEY }}" | base64
        
      - name: Push to GCR GitHub Action
        uses: RafikFarhad/push-to-gcr-github-action@v4.1
        with:
          gcloud_service_key: ${{ steps.encode_key.outputs.stdout }}
          registry: gcr.io
          project_id: ${{ env.PROJECT_ID }}
          image_name: ${{ env.IMAGE_NAME }}
          image_tag: ${{ steps.branch_name.outputs.branch_name }}-${{ steps.date.outputs.date }}
          dockerfile: ./Dockerfile
          context: ./
      
      # - name: Decode GCP_SA_KEY
      #   run: |
      #     echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > gcp-sa-key.json
        
      # - name: Configure Docker CLI
      #   run: |
      #     gcloud auth configure-docker

      # - name: Build and Push Docker Image
      #   run: |
      #     gcloud builds submit --tag gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ steps.branch_name.outputs.branch_name }}-${{ steps.commit_id.outputs.commit_id }}-${{ steps.date.outputs.date }}
      # run: |
      #     docker build -t gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ steps.branch_name.outputs.branch_name }}-${{ steps.commit_id.outputs.commit_id }}-${{ steps.date.outputs.date }} .
      #     docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ steps.branch_name.outputs.branch_name }}-${{ steps.commit_id.outputs.commit_id }}-${{ steps.date.outputs.date }}