name: AvarikCI Build 🎮

on:
  workflow_dispatch:

env:
  PROJECT_ID: agones-test-385708
  IMAGE_NAME: server_test_rifai

jobs:
  buildLinuxGameServer:
    name: Build for Linux Server
    runs-on: ubuntu-latest
    container:
      image: unityci/editor:ubuntu-2021.3.7f1-linux-il2cpp-1.1.2
      options: --user 0
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Git
        run: |
          apt-get update
          apt-get install -y git

      - name: Initialize Git repository
        run: git init

      - name: Build Unity Dedicated Server
        run: |
          mkdir -p Build
          /opt/unity/Editor/Unity \
            -quit \
            -batchmode \
            -nographics \
            -buildTarget Linux64 \
            -executeMethod BuildScript.BuildServer \
            -serial "${{ secrets.UNITY_SERIAL }}" \
            -username "${{ secrets.UNITY_EMAIL }}" \
            -password "${{ secrets.UNITY_PASSWORD }}" \
            -silent-crashes

      - name: Retrieve Git Commit ID
        run: |
          commit_id=$(git rev-parse HEAD | cut -c 1-8)
          branch_name=$(git rev-parse --abbrev-ref HEAD)
          echo "Commit ID: $commit_id"
          echo "COMMIT_ID=$commit_id" >> $GITHUB_ENV
          echo "BRANCH_NAME=$branch_name" >> $GITHUB_ENV

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Login to Google Container Registry
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GOOGLE_GCR_KEY }}

      - name: Build Docker image
        run: docker build -t gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ env.BRANCH_NAME }}-${{ env.COMMIT_ID }}-${{ steps.date.outputs.date }} .

      - name: Push Docker image
        run: docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ env.BRANCH_NAME }}-${{ env.COMMIT_ID }}-${{ steps.date.outputs.date }}