name: AvarikCI Build 🎮

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  PROJECT_ID: agones-test-385708
  IMAGE_REPOSITORY: server_test_rifai
  OUTPUT_PATH: buildserver
  ADMIN_PANEL_URL: https://firgefun.io/example_adminpanel_for_githubactoin

jobs:
  buildWindows:
    name: Build for Windows Game
    runs-on: self-hosted
    strategy:
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  #     - name: Create LFS file list
  #       run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

  #     - name: Restore LFS cache
  #       uses: actions/cache@v2
  #       id: lfs-cache
  #       with:
  #         path: .git/lfs
  #         key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

  #     - name: Git LFS Pull
  #       run: |
  #         git lfs pull
  #         git add .
  #         git reset --hard

  #     - name: Retrieve Git Commit ID
  #       run: |
  #         commit_id=$(git rev-parse HEAD | cut -c 1-8)
  #         branch_name=$(git rev-parse --abbrev-ref HEAD)
  #         echo "Commit ID: $commit_id"
  #         echo "COMMIT_ID=$commit_id" >> $GITHUB_ENV
  #         echo "BRANCH_NAME=$branch_name" >> $GITHUB_ENV

  #     - name: Get current date
  #       run: echo "today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

  #     - uses: game-ci/unity-builder@v2
  #       with:
  #         targetPlatform: StandaloneWindows64
  #         projectPath: $(pwd)
  #         buildName: avarik-fullgame-windows

      - name: Get List
        run: |
          ls -al
